### PR TITLE
Add issue templates

### PR DESCRIPTION
**Pull request by triphora**
These issue templates are based on a couple of the templates found on [PaperMC's main repository.](https://github.com/PaperMC/Paper)

### CODE REVIEW

**Comment by axieum** [comment]
It appears the new form templates are in a closed beta. But it's good that we're ready for them now! 👌

**Comment by triphora** [comment]
Fabric discord link :concern:

**Comment by axieum** [comment]
> Fabric discord link :concern:

Do you suggest a link to the Fabric issue tracker instead?

**Comment by triphora** [comment]
Maybe a placeholder for the mod dev's Discord link. Definitely not the Fabric discord link, though.

**Pull request merged**
