### PR TITLE
ci: fix condition for applying the 'assets' label

### LINKED ISSUE #20: `assets` label incorrectly applying to pull-requests
### Expected behavior

For the `assets` label to not be applied to the affected pull-request.

### Observed/actual behavior

Please refer to affected pull-request: axieum/minecord#2

### Steps/models to reproduce

Create a pull-request that does not modify any file under the `**/assets/**` file glob.

### Version

n/a

### Agreements

- [X] I am running the latest version of the mod.
- [X] My version of Minecraft is supported.
- [X] I have searched for and ensured there isn't already an open issue regarding this.

### Other

_No response_

### PR DESCRIPTION
**Pull request by nightlark**
Changes the label logic for the assets `label` from checking if any file matches any of the conditions, to any file matching all of the conditions.

Fixes #20

### CODE REVIEW

**Comment by nightlark** [comment]
My fork has a few PRs testing which labels getting applied when files in various directories are changed/modified with this fix applied to the labeler.

**Comment by axieum** [comment]
Love your work @nightlark! Very informative, and even follows the conventional commits - making this super easy to merge.

Thanks for your contribution! 🙌

**Review by axieum — APPROVED** [review]

**Comment by nightlark** [comment]
Just following the example of previous commits. :smile:

I'm not sure how you want to scope the `ci` label, but if you want the labeler could be expanded to more or less include any automation/ci workflows that don't affect `build.yml` -- something like this change: https://github.com/nightlark/fabric-example-mod/commit/39be42dc75344babe4a347089a261da4f65cd470

**Comment by nightlark** [comment]
Hey @axieum, just wanted to follow-up on the previous comment about if you wanted to expand the list of conditions before I delete my fork (and the commit referenced in it).

**Comment by axieum** [comment]
Hi @nightlark,

Yes please, that'd be grand. Can you open another PR?

Thanks,
Ax.

**Comment by nightlark** [comment]
Alright, opened as #23

**Pull request merged**
